In [11]:
#Replace NumPy array elements that doesn’t satisfy the given condition
import numpy as np
n_arr = np.array([ 122.4467 , 54.2345, 89.4567, 50.1234])
print("Given array:",n_arr)
print("Replace element in between 50. to 90.")
n_arr[n_arr > 90.] = 15.0 
print("new array:")
print(n_arr)

Given array: [122.4467  54.2345  89.4567  50.1234]
Replace element in between 50. to 90.
new array:
[15.     54.2345 89.4567 50.1234]


In [16]:
#Multiplication of p and q matrix 
p = np.matrix([[2,3] ,[4,5]])
q =np.matrix ([[3,2] , [6,3]])
print( "Matrics 1")
print(p)
print("Matrics 2")
print(q)
print("Multiplication of p and q:")
res = np.dot(p,q)
print(res)


Matrics 1
[[2 3]
 [4 5]]
Matrics 2
[[3 2]
 [6 3]]
Multiplication of p and q:
[[24 13]
 [42 23]]


In [35]:
# create an array of 10 zeros
import numpy as np
arr = np.zeros((10))
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
#create an array of 10 ones
import numpy as np 
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#create an array of 10 five 
arr = np.ones(10)
arr = arr*5
print("Array:",arr)

Array: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [37]:
#create an array of integer from 10 to 50
import numpy as np
arr = np.arange(10,51)
print("Array of integer from 10 to 50:")
arr

Array of integer from 10 to 50:


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
#create an array of even numbers from 10 to 50 
arr = np.arange(10,51,2)
print("Even numbers from 10 to 50:")
print(arr)


Even numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
#create 3*3 matrix ranging from 0 to 8 
arr = np.arange(0,9).reshape(3,3)
print('Matrix ranging from 0 to 9:')
print(arr)

Matrix ranging from 0 to 9:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#create a 3*3 matrix 
array = np.eye(3)
print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
arr = np.arange(0.01,1.01,0.01).reshape(10,10)
arr


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [9]:
arr = np.linspace(0.01,1,100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [27]:
#use numpy to generate random number between 0 & 1
arr = np.random.rand()
print("array:",arr)

array: 0.5314825542917321


In [33]:
#use a numpy to generate array of 25 random numbers sampled from standard normal distribution 
arr = np.random.randn(25)
arr

array([-3.11453404, -0.41486569, -0.79094868, -0.3877445 ,  1.792137  ,
       -1.03163967,  0.11689604,  1.53921783, -0.21148222,  1.56938074,
        0.37846612, -0.50656754,  0.89925283, -1.15373724, -0.97143929,
        0.54407443,  1.47260927, -0.64715537,  0.34947245, -1.76138348,
        0.4178877 ,  0.31205364, -0.59780303, -0.32148675, -0.23243909])

In [50]:
#create an array of 20 linearly spaced points between 0 and 1
arr=np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy and Indexing 

In [4]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
arr1 = arr[2:,1:]
arr1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [63]:
arr2 = arr[3,4]
arr2

20

In [7]:
arr3 = arr[:3,1].reshape(-1,1)  #built in function verticle then use (-1,1) 1 indicates 1 column 
arr3

array([[ 2],
       [ 7],
       [12]])

In [66]:
arr4 = arr[4]
arr4

array([21, 22, 23, 24, 25])

In [67]:
arr5 = arr[3:]
arr5

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
#Get the sum of all value in mat 
array = np.sum(arr)
array

325

In [69]:
#Get standard deviation of values in mat 
array = np.std(arr)
array

7.211102550927978

In [71]:
#Get sum of all columns in matrics 
array = np.sum(arr , axis =0) #column axis = 0 
array

array([55, 60, 65, 70, 75])